url: https://lumencube.github.io
baseurl:

# Site Settings
title: LumenCube
description: "Indie Light Bending Puzzle Game"
keywords: "Unity 3d, Indie Game Development"
google-tracking-id:

# Career Settings
# Default career thumbnail image.
career-img: "img/timeline/default.jpg"

exclude: ["Rakefile", "LICENSE", "readme.markdown"]
